### PR TITLE
actualizacion

### PR DESCRIPTION
**Pull request by era5mx**
actualizacion

### CODE REVIEW

**Comment by Saurabh3333** [comment]
Hey, Thank you for your contribution. Can you please explain to me your changes so than I can merge your request?

**Comment by Saurabh3333** [comment]
@Zaid-maker Do you want to look into this PR? What do you think?

**Comment by Zaid-maker** [comment]
Actually I don't know what does I mean. If you want you can.

**Comment by Saurabh3333** [comment]
@Zaid-maker I think, it is not important to merge this PR. Module is already working fine. Please look at the above comment again. I have updated it.

**Comment by Zaid-maker** [comment]
Of course why not i will surely 😊 do this.

**Comment by Zaid-maker** [comment]
@Saurabh3333 make sure to publish these changes to npm

**Comment by Zaid-maker** [comment]
@Saurabh3333  Is there an alternate request because request module is deprecated.

**Comment by Saurabh3333** [comment]
@Zaid-maker I have not much idea. But our module is working fine now. Right?

**Comment by Zaid-maker** [comment]
Yes absolutely fine

**Pull request closed without merging**
