### PR TITLE
Convert to es6

### PR DESCRIPTION
**Pull request by NikanZeyaei**
Converted all the function statements to arrow functions and also converted the `.then`s to the new ES6's Async/Await syntax
Also the use of the `var` keyword is prohibited in modern JavaScript so I converted all the the `var` s to their appropriate `const`s and `let`s

### CODE REVIEW

**Comment by Saurabh3333** [comment]
Thanks for the contribution. I think many people are still using the old convention. Maybe we should write something which can support both the conventions?

**Comment by NikanZeyaei** [comment]
> 
> 
> Thanks for the contribution. I think many people are still using the old convention. Maybe we should write something which can support both the conventions?

Using the old JavaScript conventions like `var` can be dangerous because of the scoping issues
Also the only browser that doesn't support Async/Await's syntactic sugar in 2021 is Microsoft's Internet Explorer
I think atleast the `var` issue in the codebase should be addressed because it can be dangerous and may lead to bugs if you decide to grow the project

**Comment by Saurabh3333** [comment]
You are right. Can you please raise one pull request just with `var` to `const` changes. If you are interested in growing this project with a sustainable approach, you are always welcome. 😊

**Comment by NikanZeyaei** [comment]
> 
> 
> You are right. Can you please raise one pull request just with `var` to `const` changes. If you are interested in growing this project with a sustainable approach, you are always welcome. 😊

Sure

**Pull request closed without merging**
