### PR TITLE
Add Jokes API Free

### PR DESCRIPTION
**Pull request by MrShoopa**
Includes Category filter

### CODE REVIEW

**Comment by Saurabh3333** [comment]
Thank for the pull request. Can you please also explain how to use it?

Please update `README.md`

**Comment by Saurabh3333** [comment]
@MrShoopa Please also explain, why you decided to improve this module? What was missing and what value are you adding?

Thank you.

**Comment by MrShoopa** [comment]
Hi @Saurabh3333, thanks for looking at my PR.

So this new function fetches the 'Joke of the Day' from Jokes.one API. Their endpoint supports fetching from [multiple categories of jokes](https://jokes.one/api/joke/).

The usage of this function can be just ``` getRandomJokeOfTheDay()```, but you can pass in a parameter with a string with any of the categories Jokes.one supports (This includes ```'knock``` or ```blonde```) for example.

**Comment by Saurabh3333** [comment]
@MrShoopa Can you please also do changes to the `README` file in the appropriate format?

**Comment by MrShoopa** [comment]
Done

**Comment by Saurabh3333** [comment]
Thank you. I have merged your code. 
Best of Luck.

**Pull request merged**
