### PR TITLE
Joke.html

### PR DESCRIPTION
**Pull request by Chandu2000**

### CODE REVIEW

**Comment by Saurabh3333** [comment]
Can you please explain what have you done?

**Comment by Chandu2000** [comment]
Hello!
It's a Random Joke generator :)

**Comment by Saurabh3333** [comment]
I can't see it.

**Comment by Saurabh3333** [comment]
It will not merge if I can't see the real changes in action.

**Comment by Chandu2000** [comment]
I created a new file. And it's a Random Joke creator.

**Comment by Saurabh3333** [comment]
Sorry!
This will not be merged. How is it helping the module? 1000s people use it every week and how your change is going to help them? Please take some time and think about it.

**Pull request closed without merging**
