### PR TITLE
Change deprecated Request to Axios

### PR DESCRIPTION
**Pull request by dephraiim**
Request as opened an issue (#10)  earlier on is deprecated. It is no longer maintained so I changed all the request requests to Axios which is a promise-based http client which is still maintained will be maintained for a long time.

### CODE REVIEW

**Comment by Zaid-maker** [comment]
Wow pretty nice dude

**Comment by dephraiim** [comment]
Thanks.

**Comment by Zaid-maker** [comment]
Yooo can we make same new package for quotes this would be cool.

**Comment by Zaid-maker** [comment]
@Saurabh3333 please merge it

**Comment by Saurabh3333** [comment]
@Zaid-maker I have merged it. Please verify it once again and let me know. After that, I will release it.

**Comment by Zaid-maker** [comment]
Ok sure I am gonna test it

**Comment by Zaid-maker** [comment]
Yes you are good to go @Saurabh3333

**Comment by Saurabh3333** [comment]
Thanks @Zaid-maker 
The new version is live now.

**Comment by Zaid-maker** [comment]
Ok

**Pull request merged**
