### PR TITLE
Update package version

### PR DESCRIPTION
**Pull request by Zaid-maker**
you forget to update the version

### CODE REVIEW

**Review by Saurabh3333 — APPROVED** [review]
Thanks

**Comment by Zaid-maker** [comment]
Yooo I have an idea can you make same like for quotes it will be awesome.

**Comment by Saurabh3333** [comment]
Yeah. It's a nice idea. Do you know some source which we may use for fetching quotes? If you get time, please do research regarding it.

**Comment by Zaid-maker** [comment]
Sure dude

**Pull request merged**
